### ISSUE TITLE
Any way to `ros2 test` from CMakeLists?

### ISSUE THREAD

**Issue by pbaughman** [ros2/ros_testing#3]
@hidmic I can't remember if this ever came up - but is there currently a way to run a ros2 launch test from a CMakeLists?

We have launch_testing_ament_cmake but that doesn't give us ROS_DOMAIN_ID isolation.

I just noticed this now as I'm getting around to migrating everything from apex_launchtest to launch_testing. . .

If we can't do this yet I will add a new package to this repo - maybe called ros2_test_ament_cmake?

Thanks

**Comment by hidmic** [comment]
@pbaughman there's the [`add_ros_test`](https://github.com/ros2/ros_testing/blob/b2ca4c0bf61103253ebaeebdf7438e85a6235ff4/ros_testing/cmake/add_ros_test.cmake#L61) CMake macro in this very same repo.

**Comment by pbaughman** [comment]
@hidmic Oof, thanks - I must be having a really bad day or something
